---
# Sets up Rita Exit service on systemd systems

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  sudo: yes
  ignore_errors: true

- name: Check iptables status
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  sudo: yes
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' 

- name: save iptables rules
  shell: "service {{item}} save"
  sudo: yes
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' 

- name: save iptables rules
  shell: "{{item}}"
  sudo: yes
  with_items:
    - "iptables-save > /etc/iptables/rules.v4"
    - "ip6tables-save > /etc/iptables/rules.v6"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Template Rita-exit service file
  template:
    src: rita.service.j2
    dest: /etc/systemd/system/rita.service
  sudo: yes
  register: rita_service

- name: Set Rita-exit to run on startup
  systemd:
    daemon_reload: yes
    name: rita
    state: restarted
    enabled: yes
  sudo: yes

- name: Wait for Quick crashes
  pause:
    seconds: 30

- name: Check if Rita is running
  command: systemctl status rita
  ignore_errors: yes
  changed_when: false
  register: service_rita_status

- name: Report status of Rita
  fail:
    msg: |
      Service rita is not running.
      Output of `systemctl status rita`:
      {{ service_rita_status.stdout }}
      {{ service_rita_status.stderr }}
  when: service_rita_status is failed
