---
# Sets up Rita Exit service on systemd systems

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: true
  ignore_errors: true

- name: Check iptables status
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  becime: true
  with_items:
    - iptables
    - ip6tables

- name: save iptables rules
  shell: "service {{item}} save"
  become: true
  with_items:
    - iptables
    - ip6tables

- name: Template Rita-exit service file
  template:
    src: rita.service.j2
    dest: /etc/systemd/system/rita.service
  become: true
  register: rita_service

- name: Set Rita-exit to run on startup
  systemd:
    daemon_reload: yes
    name: rita
    state: restarted
    enabled: yes
  become: true
