# Sets up an Althea exit node, which proxies traffic to the internet and bills for it

- name: Install Althea exit
  hosts: exit
  user: root
  serial:
  - "10%"
  - "30%"
  - "100%"
  max_fail_percentage: 10
  vars:
    enterprise: false
  roles:
    - install-deps
    - install-babel
    - install-wireguard
    - install-rita-exit
    - security
    - logrotate
    - set-qdisc
    - { role: graylog, when: enterprise }
