# Sets up an Althea exit node, which proxies traffic to the internet and bills for it

- name: Install Althea exit
  hosts: exit
  user: root
  vars:
    enterprise: true
  roles:
    - install-deps
    - install-babel
    - install-wireguard
    - install-rita-exit
    - security
    - logrotate
    - set-qdisc
    - { role: graylog, when: enterprise }
