---
# Determines if the required dependencies are installed

- name: Install Debian deps
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{debian_deps}}"
  when: ansible_distribution == 'Debian'
  sudo: yes

- name: Install Ubuntu deps
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{ubuntu_deps}}"
  when: ansible_distribution == 'Ubuntu'
  sudo: yes

- name: Install Fedora deps
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{fedora_deps}}"
  when: ansible_distribution == 'Fedora'
  sudo: yes

- name: Install CentOS/RHEL deps
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{centos_deps}}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  sudo: yes

- name: Install Archlinux Deps
  pacman:
    name: "{{item}}"
    state: present
  with_items: "{{arch_deps}}"
  when: ansible_distribution == 'Archlinux'
  sudo: yes
