---

- name: Enable Debian Unstable
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present
  sudo: yes

- name: Set unstable packages as low priority
  blockinfile:
    path: /etc/apt/preferences.d/limit-unstable
    create: true
    block: |
      Package: *
      Pin: release a=unstable
      Pin-Priority: 150
  sudo: yes

- name: Install wireguard
  apt:
    name: "{{item}}{{wireguard_version}}"
    update_cache: yes
  sudo: yes
  with_items:
    - wireguard
