---

- name: Enable copr
  shell: dnf copr enable jdoss/wireguard
  become: true

- name: Install wireguard
  dnf:
    name: "{{item}}"
    state: latest
  become: true 
  with_items:
    - wireguard-dkms
    - wireguard-tools
