---

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- include_tasks: rhel.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: arch.yml
  when: ansible_distribution == 'Archlinux'
