---

- name: Download repo file
  get_url:
    url: "{{wireguard_rhel_repo}}"
    dest: /etc/yum.repos.d/wireguard.repo
  sudo: yes

- name: Install epel
  yum:
    name: epel-release
    state: present
  sudo: yes

- name: Install wireguard
  yum:
    name: "{{item}}{{wireguard_version}}"
  sudo: yes
  with_items:
    - wireguard-dkms
    - wireguard-tools
