---

- name: Add wireguard repo
  apt_repository:
    repo: "ppa:wireguard/wireguard"
  sudo: yes

- name: Install wireguard
  apt:
    name: "{{item}}{{wireguard_version}}"
    update_cache: yes
  sudo: yes
  with_items:
    - wireguard
