---
# Sets up Babeld service on systemd systems

- name: Template Babeld service file
  template:
    src: babeld.service.j2
    dest: /etc/systemd/system/babeld.service
  become: true

- name: Set babeld to run on startup
  systemd:
    daemon_reload: yes
    name: babeld
    state: started
    enabled: yes
  become: true
