---
# Sets up the babeld as a system service

- name: Check for Rita Exit bianry
  local_action: stat path="{{playbook_dir}}/rita_exit"
  register: rita_exit_bin

- name: Rita bin not present, download latest release
  get_url:
    url: "{{rita_exit_bin_url}}"
    dest: "/usr/bin/rita_exit"
    mode: 0755
    force: true
  become: true
  when: not rita_exit_bin.stat.exists

- name: Copy rita-exit binary
  copy:
    src: "{{playbook_dir}}/rita_exit"
    dest: /usr/bin/rita_exit
    mode: 0755
  become: true
  when: rita_exit_bin.stat.exists

- name: Create database dir
  file:
    path: "{{database_dir}}"
    state: directory
  become: true

- name: Check for database
  stat:
    path: "{{database_dir}}/exit.db"
  become: true
  register: database

- name: Copy empty db
  get_url:
    url:  "{{blank_db_url}}"
    dest: "{{database_dir}}/exit.db"
    backup: yes
  become: true
  when: not database.stat.exists

- name: Stop the process to update config
  systemd:
    name: rita-exit
    state: stopped
    enabled: yes
  become: true
  ignore_errors: true

- name: Copy the rita-exit config
  template:
    src: rita_exit.toml.j2
    dest: /etc/rita-exit.toml
  become: true

- name: Fail on nonsystemd systems
  fail:
    msg: "No support for non systemd services, please add support for your init system!"
  when: "ansible_service_mgr != 'systemd'"

- include_tasks: systemd.yml

- name: Open Rita port
  iptables:
    chain: INPUT
    protocol: "{{item[0]}}"
    destination_port: "{{item[1]}}"
    jump: ACCEPT
    ip_version: "{{item[2]}}"
    ctstate: NEW
  become: true
  with_nested:
    - ["tcp", "udp"]
    - ["{{rita_port}}", "{{bounty_port}}", "{{exit_registration_port}}"]
    - ["ipv4", "ipv6"]

- name: Open WireGuard port range
  iptables:
    chain: INPUT
    destination_port: "{{firewall_start_port}}:"
    protocol: udp
    ip_version: "{{item}}"
    jump: ACCEPT
    ctstate: NEW
  become: true
  with_items:
    - ipv4
    - ipv6
