# Sets up the babeld as a system service

- name: Check for Rita Exit bianry
  local_action: stat path="{{playbook_dir}}/rita_exit"
  register: rita_exit_bin

- name: Rita bin not present, download latest release
  get_url:
    url: "{{rita_exit_bin_url}}"
    dest: "/usr/bin/rita_exit"
    mode: 0755
    force: true
  sudo: yes
  when: not rita_exit_bin.stat.exists

- name: Copy rita-exit binary
  copy:
    src: "{{playbook_dir}}/rita_exit"
    dest: /usr/bin/rita_exit
    mode: 0755
  sudo: yes
  when: rita_exit_bin.stat.exists

- name: Create database dir
  file:
    path: "{{database_dir}}"
    state: directory
  sudo: yes

- name: Check for database
  stat:
    path: "{{database_dir}}/exit.db"
  sudo: yes
  register: database

- name: Backup database
  fetch:
    src: "{{database_dir}}/exit.db"
    dest: "backup/{{ansible_fqdn}}/"
    validate_checksum: yes
  sudo: yes
  when: database.stat.exists

- name: Copy empty db
  get_url:
    url: "{{blank_db_url}}"
    dest: "{{database_dir}}/exit.db"
    backup: yes
  sudo: yes
  when: not database.stat.exists

- name: Fail on nonsystemd systems
  fail:
    msg: "No support for non systemd services, please add support for your init system!"
  when: "ansible_service_mgr != 'systemd'"

- name: Stop the process to update config
  systemd:
    name: rita-exit
    state: stopped
    enabled: yes
  sudo: yes
  ignore_errors: true

- name: Copy the rita-exit config
  template:
    src: rita_exit.toml.j2
    dest: /etc/rita-exit.toml
  sudo: yes

- name: Open Rita port
  iptables:
    chain: INPUT
    protocol: "{{item[0]}}"
    destination_port: "{{item[1]}}"
    jump: ACCEPT
    ip_version: "{{item[2]}}"
    ctstate: NEW
  sudo: yes
  with_nested:
    - ["tcp", "udp"]
    - ["{{rita_port}}", "{{bounty_port}}", "{{exit_registration_port}}"]
    - ["ipv4", "ipv6"]

- name: Open WireGuard port range
  iptables:
    chain: INPUT
    destination_port: "{{firewall_start_port}}:"
    protocol: udp
    ip_version: "{{item}}"
    jump: ACCEPT
    ctstate: NEW
  sudo: yes
  with_items:
    - ipv4
    - ipv6

- name: Tune sysctl limits
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^fs.file-max="
    line: "fs.file-max=1073741824"
    state: present
  sudo: yes

- name: Tune process soft limit
  lineinfile:
    path: /etc/security/limits.conf
    regexp: "^\\* soft"
    line: "* soft nofile 500000"
    state: present
  sudo: yes

- name: Tune process hard limit
  lineinfile:
    path: /etc/security/limits.conf
    regexp: "^\\* hard"
    line: "* hard nofile 500000"
    state: present
  sudo: yes

- name: Reload sysctl
  shell: "sysctl -p"
  sudo: yes

- include_tasks: systemd.yml
