---
# Sets up Rita Exit service on systemd systems

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: true
  ignore_errors: true

- name: Check iptables status
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  becime: true
  with_items:
    - iptables
    - ip6tables

- name: save iptables rules
  shell: "service {{item}} save"
  become: true
  with_items:
    - iptables
    - ip6tables

- name: Template Rita-exit service file
  template:
    src: rita-exit.service.j2
    dest: /etc/systemd/system/rita-exit.service
  become: true
  register: rita_exit_service

- name: Set Rita-exit to run on startup
  systemd:
    daemon_reload: yes
    name: rita-exit
    state: restarted
    enabled: yes
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 30

- name: Check if Rita-exit is running
  command: systemctl status rita-exit
  ignore_errors: yes
  changed_when: false
  register: rita_exit_status

- name: Report status of Rita-exit
  fail:
    msg: |
      Service rita-exit is not running.
      Output of `systemctl status rita-exit`:
      {{ service_rita_exit_status.stdout }}
      {{ service_rita_exit_status.stderr }}
  when: rita_exit_status is failed
